### ISSUE TITLE
Any plans to add actual re-packing?

### ISSUE THREAD

**Issue by dullcibus** [neofright/sabnzbd_srrdb#2]
Do you have any plans to add actual re-packing to the script?

(Btw. perhaps looking at rescepy for inspiration would be beneficial: https://github.com/dryes/rescepy )

**Comment by neofright** [comment]
@dullcibus Can I ask why you would want this feature?

I made this with the intention that it would only be used via SAB / NZBGet as a post-processing script.

Having srr files and being able to verify a copy of a release allows backfilling by re-creating orars and re-uploading them in the future.
I always imagined that this was a out of scope for this post-processing script.

**Comment by dullcibus** [comment]
I like having releases in their original form.
So far I've been manually processing downloaded content from nzbget with rescepy, I was just about to create a wrapper script for rescepy to be able to use it with nzbget when I came across your script.

Perhaps a re-pack option could be a optional feature? Although I'm not sure if it's possible to have configurable options with post-processing scripts

**Comment by neofright** [comment]
Are you using something like rar2fs to actually consume the content?

Would it be sufficient to just do this:

```
#!/usr/bin/env bash
curl "https://www.srrdb.com/download/srr/$SAB_FINAL_NAME" --output "${SAB_COMPLETE_DIR}/${SAB_FINAL_NAME}.srr"
srr.py -y -t "$SAB_COMPLETE_DIR" -o "$SAB_COMPLETE_DIR" -i "$SAB_COMPLETE_DIR" "$SAB_COMPLETE_DIR"/*.srr -z "/path/to/rarlinux/binaries"
```

The simplest way for the script to account for both that I can think of would be to have a separate category in sab for orars which the script can just check via `SAB_CAT`.

I don't think I will add this functionality any time soon.

**Comment by dullcibus** [comment]
Thanks, this got me started in the right direction, I ended up doing this:

```bash
#!/usr/bin/env bash
rescepy="/usr/bin/env rescepy"

for x in $(ls -1 --ignore="*."{nfo,sfv,nzb,srr,srs,txt,} $SAB_COMPLETE_DIR);
        do $rescepy  $SAB_COMPLETE_DIR/$x;

```

**Comment by neofright** [comment]
I'm glad you got something working for yourself.

Beware of iterating the output of ls as explained [here](https://mywiki.wooledge.org/ParsingLs).
