### ISSUE TITLE
Indexers with pred=1?

### ISSUE THREAD

**Issue by dullcibus** [neofright/sabnzbd_srrdb#4]
Any chance you could share a name of a indexer that supports the `&pred=1` extended attribute, or is that a sensitive subject?

I looked at a few popular ones but unfortunately haven't been able to find a indexer that supports it.

Thanks!

**Comment by neofright** [comment]
The 9th indexer in [this](https://github.com/Sonarr/Sonarr/tree/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Indexers) list.
