### ISSUE TITLE
remove SRR file after verification

### ISSUE THREAD

**Issue by bambury** [neofright/sabnzbd_srrdb#6]
The title says it all - I think it's redundant to keep the SRR file after use. Maybe it could be an option?

And by the way, thanks for making this script!

**Comment by neofright** [comment]
My two reasons for keeping the srr file:

1. It makes future re-uploading/backfilling easier as you can regenerate the oRARs.
2. If you suspect data corruption or have your media on disks without parity you can verify your releases.

Although you might think its redundant, most srr files are < 1MB so I personally don't see them as a hindrance.

It should be pretty straightforward to add an option to delete the srr files after verifying. I'll think about  how to do it and try and add it to a future release.

Please do report any other bugs you may find.

**Comment by bambury** [comment]
Hi,

thanks for your reply! Your reasons make absolute sense, although they would probably not apply to my use case. So if you ever added this, it should definitely be an option. :)

Oh, and no bugs found!

**Comment by neofright** [comment]
Commit https://github.com/neofright/sabnzbd_srrdb/commit/0a99c6f3626ffcfe80f06eb5a176b639f4741263 should do what you want.

You'll need to download the master copy of this repo and search for `remove_valid_srr` and set it to `remove_valid_srr = True`.

Let me know if it works for you and I'll release 0.4.

**Comment by bambury** [comment]
Thanks for the quick response! It works perfectly for both audio and video.

Just a note: `remove_valid_srr` is already set to True in your code (in case you want it to default to False in the release).

**Comment by neofright** [comment]
Yep, good catch, I had intended the default state to be False!

Closing the issue, glad it works.
